
ccflags-y += -DCHIP_TYPE_hi3798cv100

ccflags-y += -DHI_DISP_BUILD_FULL
ccflags-y += -D__DISP_PLATFORM_SDK__

ccflags-y += -Idrivers/msp/include
ccflags-y += -Idrivers/msp/vo/vdp_v1_0/alg
ccflags-y += -Idrivers/msp/vo/vdp_v1_0/com
ccflags-y += -Idrivers/msp/vo/vdp_v1_0/drv
ccflags-y += -Idrivers/msp/vo/vdp_v1_0/hal/common
ccflags-y += -Idrivers/msp/vo/vdp_v1_0/hal/cv200

obj-y += vdp_v1_0/drv_disp.o
obj-y += vdp_v1_0/drv_disp_adp2unf.o
obj-y += vdp_v1_0/alg/drv_disp_alg_csc.o
obj-y += vdp_v1_0/alg/drv_disp_alg_rgb2yuv.o
obj-y += vdp_v1_0/alg/drv_disp_alg_zme.o
obj-y += vdp_v1_0/com/drv_disp_debug.o
obj-y += vdp_v1_0/com/drv_disp_osal.o
obj-y += vdp_v1_0/drv/drv_display.o
obj-y += vdp_v1_0/drv/drv_disp_buffer.o
obj-y += vdp_v1_0/drv/drv_disp_cast.o
obj-y += vdp_v1_0/drv/drv_disp_isr.o
obj-y += vdp_v1_0/hal/common/drv_disp_da.o
obj-y += vdp_v1_0/hal/common/drv_disp_hal.o
obj-y += vdp_v1_0/hal/common/drv_disp_ua.o
obj-y += vdp_v1_0/hal/cv200/vdp_driver.o
obj-y += vdp_v1_0/hal/cv200/hal_specific_config.o


