
ccflags-y += -DCHIP_TYPE_hi3798cv100
ccflags-y += -DCFG_HI_HD0_FB_VRAM_SIZE=16200
ccflags-y += -DCFG_HIFB_STEREO3D_HW_SUPPORT

ccflags-y += -Idrivers
ccflags-y += -Idrivers/msp/include

obj-y += hifb_main.o
