
ccflags-y += -DCHIP_TYPE_hi3798cv100
ccflags-y += -DCFG_HI_HD0_FB_VRAM_SIZE=16200
ccflags-y += -DCFG_HIFB_STEREO3D_HW_SUPPORT
ccflags-y += -DCFG_HIFB_FENCE_SUPPORT
ccflags-y += -DHI_PROC_SUPPORT=1

ccflags-y += -Idrivers/staging/android
ccflags-y += -Idrivers/msp/include

obj-y += hifb_fence.o
obj-y += hifb_main.o
