
ccflags-y += -Idrivers/msp/include
ccflags-y += -Idrivers/msp/adsp/adsp_v1_1/include
ccflags-y += -Idrivers/msp/mce/include
ccflags-y += -DCHIP_TYPE_hi3716cv200
ccflags-y += -DLOG_UDISK_SUPPORT
ccflags-y += -DHI_PROC_SUPPORT

obj-y += drv_base_ext.o
obj-y += drv_base_ext_k.o
obj-y += drv_dev_ext_k.o
obj-y += drv_file_ext.o
obj-y += drv_log_ext_k.o
             #obj-y += drv_media_mem.o
obj-y += drv_module_ext.o
obj-y += drv_mmz_intf.o
obj-y += drv_mmz_ext_k.o
obj-y += drv_mmz_intf.o
			#obj-y += drv_mmz_userdev.o
obj-y += drv_mutils.o
obj-y += drv_osal.o
obj-y += drv_proc_ext_k.o
obj-y += drv_stat_ext_k.o
obj-y += drv_sys_ext_k.o

obj-y += base/hi_init.o
obj-y += mce/drv_mce_intf.o
obj-y += mce/drv_mce_play.o
