
ccflags-y += -Idrivers/msp/include

obj-y += drv_base_ext_k.o
obj-y += drv_dev_ext_k.o
obj-y += drv_log_ext_k.o
#obj-y += drv_media_mem.o
#obj-y += drv_media_mem_v2.o
#obj-y += drv_mmz_ext_k.o
#obj-y += drv_mmz_intf.o
obj-y += drv_osal.o
obj-y += drv_proc_ext_k.o

obj-y += base/hi_init.o