#ifndef __TDE_CONFIG_H__
#define __TDE_CONFIG_H__

//#define CONFIG_TDE_PROC_DISABLE
//#define CONFIG_TDE_VERSION_DISABLE
//#define CONFIG_TDE_STR_DISABLE
//#define CONFIG_TDE_DEBUG_DISABLE
#define HI_TDE_BITMAPMASK_SUPPORT 0
#endif