
ccflags-y += -Idrivers/msp/include
ccflags-y += -Idrivers/msp/adsp/adsp_v1_1/include
ccflags-y += -Idrivers/msp/mce/include
ccflags-y += -DCHIP_TYPE_hi3716cv200
ccflags-y += -DHI_PROC_SUPPORT

obj-y += himedia/himedia.o
obj-y += himedia/himedia_base.o

obj-y += mmz/drv_mmz_userdev.o
obj-y += mmz/drv_media_mem.o
