
ccflags-y += -DCHIP_TYPE_hi3798cv100
ccflags-y += -DHI_PROC_SUPPORT=1
ccflags-y += -DCFG_HI_TDE_CSCTMPBUFFER_SIZE=0
ccflags-y += -DHI_TDE_UNIT64_NUM=200
ccflags-y += -DHI_TDE_UNIT128_NUM=348
ccflags-y += -DHI_TDE_UNIT1024_NUM=8
ccflags-y += -DHI_TDE_BUFFER=0x20000
#ccflags-y += -DHI_TDE_BITMAPMASK_SUPPORT

ccflags-y += -Idrivers/msp/include

obj-y += tde_osr_k.o
obj-y += tde_hal_k.o
obj-y += tde_handle_k.o
obj-y += tde_osilist_k.o
obj-y += tde_osictl_k.o
obj-y += tde_proc_k.o
obj-y += wmalloc_k.o



