
ccflags-y += -DCHIP_TYPE_hi3798cv100
ccflags-y += -DDVI_SUPPORT
ccflags-y += -DCEC_SUPPORT 
ccflags-y += -DHDCP_SUPPORT
ccflags-y += -DANDROID_SUPPORT
ccflags-y += -DHI_PROC_SUPPORT=1

ccflags-y += -Idrivers/msp/include
ccflags-y += -Idrivers/msp/hdmi
ccflags-y += -Idrivers/msp/hdmi/hdmi_drv


obj-y += hdmi_intf_k.o #complete
obj-y += hdmi_intf.o #complete
obj-y += drv_hdmi.o #complete
obj-y += drv_global.o #complete
obj-y += drv_reg_proc.o #complete
obj-y += drv_compatibility.o #complete
obj-y += hdmi_drv/drv_hlviic.o #complete
obj-y += hdmi_drv/si_audio.o #complete
obj-y += hdmi_drv/si_cec.o #complete
obj-y += hdmi_drv/si_crc16.o #complete
obj-y += hdmi_drv/si_de.o #complete
obj-y += hdmi_drv/si_delay.o #complete
obj-y += hdmi_drv/si_edid.o #complete
obj-y += hdmi_drv/si_eeprom.o #complete
obj-y += hdmi_drv/si_hdcp.o
obj-y += hdmi_drv/si_hdmitx.o
obj-y += hdmi_drv/si_infofrm.o
obj-y += hdmi_drv/si_isr.o
obj-y += hdmi_drv/si_mddc.o
obj-y += hdmi_drv/si_regio.o
obj-y += hdmi_drv/si_timer.o
obj-y += hdmi_drv/si_txvidp.o
obj-y += hdmi_drv/si_ucec.o
obj-y += hdmi_drv/si_video.o
obj-y += hdmi_drv/si_vmode.o
obj-y += hdmi_drv/si_vmtables.o
obj-y += hdmi_drv/si_phy.o #complete
